### ISSUE TITLE
Command Line Flags should overwrite config file values.

### ISSUE THREAD

**Issue by bradcypert** [bradcypert/deckard#5]
As a user, I may want to keep everything in a config file EXCEPT for a password. If I provide a config file and a flag, the flag should override the config value.

**Comment by kergeodeta** [comment]
Hi! I relatively new here, can I work on this issue?

**Comment by bradcypert** [comment]
Absolutely. If you'd like some tips, lemme know :)

**Comment by bradcypert** [comment]
@kergeodeta need any help with this one?

**Comment by bradcypert** [comment]
Fixed in #26
